prose:
  rooturl: "content"
  media: "content/images/"
  metadata:
    content:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          help: "Some relevant tags"
          alterable: true
          placeholder: "Select ..."
          options:
            # Tip dogodka
            - name: delavnica
              value: delavnica
            - name: druženje
              value: druženje
            - name: okrogla miza
              value: okrogla miza
            - name: predavanje
              value: predavanje
            - name: sestanek
              value: sestanek

            # Redne programske značke
            - name: bitcoin
              value: bitcoin
            - name: coderdojo
              value: coderdojo
            - name: igrolog
              value: igrolog
            - name: filmšteka
              value: filmšteka
            - name: fsfe
              value: fsfe
            - name: kiberpipa
              value: kiberpipa
            - name: meet-up
              value: meet-up
            - name: pot
              value: pot

            # Ostale značke
            - name: igre
              value: igre
            - name: oblikovanje
              value: oblikovanje
            - name: programiranje
              value: programiranje
            - name: za otroke
              value: za otroke
      - name: "category"
        field:
          element: "select"
          label: "Category"
          help: "Note, the category should be inferred from the file directory, DO NOT set it here!"
          alterable: true
          placeholder: "Select one, or NONE. DON'T set anything here!"
          options:
            # Redni program
            - name: CoderDojo
              value: CoderDojo
            - name: Filmšteka
              value: Filmšteka
            - name: FSFE
              value: FSFE
            - name: Kiberpipa
              value: Kiberpipa
            - name: POT
              value: POT
            - name: Reciklarna
              value: Reciklarna
            - name: Servis
              value: Servis

            # Izredni program
            - name: Igrolog
              value: Igrolog
            - name: Bitcoin
              value: Bitcoin
            - name: Zunanji
              value: Zunanji
      - name: "date"
        field:
          element: "text"
          label: "Date & time"
          help: "Date and time of the event in ISO format (e.g. '2013-09-13 14:00')"
      - name: "dates"
        field:
          element: "textarea"
          label: "Recurring Datetimes"
          help: "List of dates if recurring event (e.g. '- 2014-10-27 16:20  # visitors: 19')"
      - name: "duration"
        field:
          element: "text"
          label: "Event duration"
          help: "Duration of the event in HH:MM (e.g. 04:00)"
      - name: "location"
        field:
          element: "select"
          label: "Event Location"
          help: "Only set location if NOT the default (Kiberpipa)."
          placeholder: "Select one ..."
          options:
            - name: "Kiberpipa"
              value: "Kiberpipa"
            - name: "KOŽ"
              value: "Mediateka KOŽ"
            - name: "Učilnica"
              value: "Računalniška učilnica @ KOŽ"
      - name: "video"
        field:
          element: "text"
          label: "Video stream URL"
          help: "URL to a YouTube video or playlist"
      - name: "gallery"
        field:
          element: "text"
          label: "Photo gallery URL"
          help: "URL to a Facebook photo album"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Publish the content, or make it hidden"
          value: true
