prose:
  rooturl: 'content'
  metadata:
    content:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          alterable: true
          placeholder: "Choose Tags"
          options:
            # Tip dogodka
            - name: delavnica
              value: delavnica
            - name: druženje
              value: druženje
            - name: okrogla miza
              value: okrogla miza
            - name: predavanje
              value: predavanje
            - name: sestanek
              value: sestanek

            # Redne programske značke
            - name: bitcoin
              value: bitcoin
            - name: coderdojo
              value: coderdojo
            - name: igrolog
              value: igrolog
            - name: filmšteka
              value: filmšteka
            - name: fsfe
              value: fsfe
            - name: kiberpipa
              value: kiberpipa
            - name: meet-up
              value: meet-up
            - name: pot
              value: pot

            # Ostale značke
            - name: igre
              value: igre
            - name: oblikovanje
              value: oblikovanje
            - name: programiranje
              value: programiranje
            - name: za otroke
              value: za otroke
      - name: "category"
        field:
          element: "select"
          label: "Add Tags"
          alterable: true
          placeholder: "Choose Category"
          options:
            # Redni program
            - name: CoderDojo
              value: CoderDojo
            - name: Filmšteka
              value: Filmšteka
            - name: FSFE
              value: FSFE
            - name: Kiberpipa
              value: Kiberpipa
            - name: POT
              value: POT
            - name: Reciklarna
              value: Reciklarna
            - name: Servis
              value: Servis

            # Izredni program
            - name: Igrolog
              value: Igrolog
            - name: Bitcoin
              value: Bitcoin
            - name: Zunanji
              value: Zunanji
      - name: "date"
        field:
          element: "text"
          label: "Choose Datetime"
          help: "Event date and time (2013-09-13 14:00)"
      - name: "dates"
        field:
          element: "textarea"
          label: "Choose Datetimes"
          help: "List of event dates (- 2014-10-27 16:20  # visitors: 190)"
      - name: "duration"
        field:
          element: "text"
          label: "Choose duration"
          help: "Event duration (04:00)"
      - name: "location"
        field:
          element: "select"
          label: "Select Location"
          placeholder: "Location"
          options:
            - name: "kiberpipa"
              value: "Kiberpipa"
            - name: "kož"
              value: "Mediateka KOŽ"
      - name: "video"
        field:
          element: "text"
          label: "Choose Video"
          help: "Youtube video or playlist url"
      - name: "gallery"
        field:
          element: "text"
          label: "Choose Gallery"
          help: "Facebook image gallery url"
